# Generated by Django 2.2.23 on 2021-05-23 13:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_survey', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BlockDetailsMaster',
            fields=[
                ('block_name', models.CharField(max_length=50)),
                ('id', models.IntegerField(primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='DistrictDetailsMaster',
            fields=[
                ('district_name', models.CharField(max_length=50)),
                ('id', models.IntegerField(primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='WardDetailsMaster',
            fields=[
                ('ward_name', models.CharField(max_length=50)),
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('block_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_survey.BlockDetailsMaster')),
                ('district_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_survey.DistrictDetailsMaster')),
            ],
        ),
        migrations.AlterField(
            model_name='userdetails',
            name='block',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_survey.BlockDetailsMaster'),
        ),
        migrations.AlterField(
            model_name='userdetails',
            name='district',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_survey.DistrictDetailsMaster'),
        ),
        migrations.AlterField(
            model_name='userdetails',
            name='vaccination_status',
            field=models.CharField(choices=[('Yes', 'Vaccinated'), ('No', 'Not Vaccinated')], default='No', max_length=3),
        ),
        migrations.AlterField(
            model_name='userdetails',
            name='ward',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_survey.WardDetailsMaster'),
        ),
        migrations.AddField(
            model_name='blockdetailsmaster',
            name='district_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_survey.DistrictDetailsMaster'),
        ),
    ]
